# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJi5tMaq8a4hBNbVawyRhH7A3g73WvH2
"""

# Install a library, for example, pandas
!pip install pandas

# After installation, you can import and use the library
import pandas as pd
print(f'pandas version: {pd.__version__}')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Data Loading**"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("gokulrajkmv/unemployment-in-india")

print("Path to dataset files:", path)

import os

# The 'path' variable from the previous cell contains the directory where the dataset was downloaded.
# We need to specify the full path to the CSV file.
# A common file name for this dataset is 'Unemployment in India.csv'.
file_path = os.path.join(path, 'Unemployment in India.csv')

# Load the CSV file into a pandas DataFrame named 'data'
data = pd.read_csv(file_path)

# Now, you can display the head of the DataFrame
data.head()

data.tail()

data.info()

data.describe()

"""**Data Cleaning**"""

data.columns

data.columns = data.columns.str.strip()

data.rename(columns={
    'Estimated Unemployment Rate (%)': 'Unemployment_Rate',
    'Estimated Employed': 'Employed',
    'Estimated Labour Participation Rate (%)': 'Labour_Participation_Rate'
}, inplace=True)

data['Date'] = pd.to_datetime(data['Date'])

print(data.isnull().sum())

data.head()

data.tail()

"""**Exploratory Data Analysis (EDA)**"""

print(data.describe())

avg_unemployment = data['Unemployment_Rate'].mean()
print("Average Unemployment Rate:", avg_unemployment)

highest_region = data.groupby('Region')['Unemployment_Rate'].mean().sort_values(ascending=False)

print(highest_region.head())

plt.figure(figsize=(12,6))

plt.plot(data['Date'], data['Unemployment_Rate'])

plt.title('Unemployment Rate Over Time')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')

plt.xticks(rotation=45)

plt.show()

"""**COVID-19 Impact Analysis**"""

covid_period = data[data['Date'] >= '2020-03-01']

before_covid = data[data['Date'] < '2020-03-01']['Unemployment_Rate'].mean()

during_covid = covid_period['Unemployment_Rate'].mean()

print("Before COVID:", before_covid)
print("During COVID:", during_covid)

plt.figure(figsize=(12,6))

plt.plot(data['Date'], data['Unemployment_Rate'], label='Unemployment Rate')

plt.axvline(pd.to_datetime('2020-03-01'),
            color='red',
            linestyle='--',
            label='COVID-19 Start')

plt.legend()

plt.title('Impact of COVID-19 on Unemployment')

plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')

plt.show()

"""**Regional Analysis**"""

top_regions = data.groupby('Region')['Unemployment_Rate'].mean().sort_values(ascending=False).head(10)

top_regions.plot(kind='bar', figsize=(10,6))

plt.title('Top Regions with Highest Unemployment')
plt.ylabel('Unemployment Rate (%)')

plt.show()

area_analysis = data.groupby('Area')['Unemployment_Rate'].mean()

print(area_analysis)

area_analysis.plot(kind='bar')

plt.title('Rural vs Urban Unemployment')
plt.ylabel('Average Unemployment Rate (%)')

plt.show()

"""**Seasonal Trend Analysis**"""

data['Month'] = data['Date'].dt.month

monthly_trend = data.groupby('Month')['Unemployment_Rate'].mean()

print(monthly_trend)

monthly_trend.plot(marker='o', figsize=(10,5))

plt.title('Seasonal Unemployment Trend')

plt.xlabel('Month')
plt.ylabel('Average Unemployment Rate (%)')

plt.grid()

plt.show()

correlation = data[['Unemployment_Rate',
                  'Employed',
                  'Labour_Participation_Rate']].corr()

print(correlation)

sns.heatmap(correlation,
            annot=True,
            cmap='coolwarm')

plt.title('Correlation Matrix')

plt.show()

# Export the cleaned dataset to a CSV file
data.to_csv('unemployment_cleaned.csv', index=False)
print('Cleaned dataset exported to unemployment_cleaned.csv')

data.to_csv('unemployment_cleaned.csv', index=False)
print('Cleaned dataset exported to unemployment_cleaned.csv')